[pytest]

;base_url=http://47.116.12.183/

addopts = -p no:playwright
          --base-url=http://47.116.12.183/
          --tracing=retain-on-failure
          --screenshot=only-on-failure
          --video=retain-on-failure

log_cli = true
log_level = info